version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: la-base-portfolio
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=portfolio
      - DB_USERNAME=root
      - DB_PASSWORD=RealMadrid04@
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: postgres:16
    container_name: portfolio_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: root
      POSTGRES_PASSWORD: RealMadrid04@
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
